name: Dispatch a SSH session

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Leave only desired OS in the field'
        required: true
        default: 'ubuntu-24.04'
jobs:
  start_ssh_session:
    runs-on: ${{ github.event.inputs.os }}
    name: Start the SSH session
    steps:
    - name: Start SSH session
      uses: luchihoratiu/debug-via-ssh@main
      with:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
        NGROK_TIMEOUT: 25001
ko_fi: dede_klender # Replace with a single Ko-fi username
custom: ['teer.id/dede_klender'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
